global:
  smtp_smarthost: host.docker.internal:25
  smtp_from: alertmanager@sid1.local
  smtp_require_tls: false
  resolve_timeout: 5m
route:
  receiver: airflow-ops-email
  group_by: [alertname, environment, hostname]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  routes:
    - matchers: ['severity="critical"']
      receiver: airflow-ops-email
      repeat_interval: 1h
receivers:
  - name: airflow-ops-email
    email_configs:
      - to: airflow-ops@example.org
        send_resolved: true
        headers:
          Subject: '[Airflow {{ .Status | toUpper }}] {{ .CommonLabels.alertname }} - {{ .CommonLabels.environment }}'
inhibit_rules:
  - source_matchers: ['severity="critical"']
    target_matchers: ['severity="warning"']
    equal: [alertname, hostname]
